### ISSUE TITLE
[FEAT] redesign the tvm model

### ISSUE THREAD

**Issue by Alec4r** [eduNEXT/tvm#10]
### Discussed in https://github.com/eduNEXT/tvm/discussions/8
<sup>Originally posted by **Alec4r** May 13, 2022</sup>

- [x] #11
- [x] #12

**Comment by Alec4r** [comment]
You can test the new features using the branch: **10_redesign_the_tvm_model**

**Comment by MaferMazu** [comment]
- [ ] I can't activate tvm environment in a different path

**Comment by Alec4r** [comment]
The two pull requests were merged.
