### ISSUE TITLE
[BUG] tutor switcher does not show my config when the tvm environment is active

### ISSUE THREAD

**Issue by felipemontoya** [eduNEXT/tvm#20]
**Describe the bug**
When I run `tutor --version` in an active tvm environment (e.g. v13.2.2@GqTXDukMmd) it says:

You have not selected any config. Tutor will use the global default ~.local/share/tutor

Which is not true, because
tutor config printroot -> `/data/tools/tvm-open/example_1`

**To Reproduce**

```
mkdir example_1
cd example_1/
tvm project init
source .tvm/bin/activate
tutor --version
tutor config printroot
```

**Expected behavior**
It should either not say anything, or show the correct path of the TUTOR_ROOT

**Desktop (please complete the following information):**
 - OS:
Distributor ID:	Linuxmint
Description:	Linux Mint 20.2
Release:	20.2
Codename:	uma

 - TVM Version: latest master

**Comment by felipemontoya** [comment]
Maybe the solution is to have the tutor_switcher look at the value of TUTOR_ROOT directly instead of requiring this value for the template.

**Comment by Alec4r** [comment]
@felipemontoya this will be fixed on the PR: feat: add tvm config commands
