### ISSUE TITLE
[BUG] tvm not installing vitualenv

### ISSUE THREAD

**Issue by dsg-edn** [eduNEXT/tvm#42]
**Describe the bug**
When tvm is being installed is expected to install virtualenv as it is a requirement for it to run properlly. 

**To Reproduce**
1. tvm install <version>

**Expected behavior**
When running the comman virtualenv should be installed by default without needing to pip install it

**Comment by Henrrypg** [comment]
Bug fixed in https://github.com/eduNEXT/tvm/releases/tag/v2.0.1
