### ISSUE TITLE
[BUG] docs: user guide files has incorrect paths

### ISSUE THREAD

**Issue by JuanDavidBuitrago** [eduNEXT/tvm#56]
**Describe the bug**
The paths of [Tutor Version Manager](https://github.com/eduNEXT/tvm/blob/main/docs/TutorVersionManager.rst) and [Tutor enVironment Manager](https://github.com/eduNEXT/tvm/blob/main/docs/TutorEnvironmentManager.rst) are incorrect

**To Reproduce**
Go to https://github.com/eduNEXT/tvm#user-guide click on *Tutor Version Manager* or *Tutor enVironment Manager*

**Expected behavior**
The request response is 404

**Comment by MaferMazu** [comment]
Thanks @JuanDavidBuitrago, We're going to update the README soon 😊
