### ISSUE TITLE
Issue with Multiple Open edX Instances on Single Server Using TVM

### ISSUE THREAD

**Issue by Mahendra-TitanEd** [eduNEXT/tvm#74]
Any idea for this: https://discuss.openedx.org/t/issue-with-multiple-open-edx-instances-on-single-server-using-tvm/13182

**Comment by MaferMazu** [comment]
I will leave the answer from Felipe here: https://discuss.openedx.org/t/issue-with-multiple-open-edx-instances-on-single-server-using-tvm/13182/4?u=mafermazu.
I'll close this issue, but if you need anything else, please re-open it.

Thanks
